name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-c:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y cmake cppcheck

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Static Analysis
        run: make check

  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python dependencies
        run: pip install -r python/requirements.txt

      - name: Test
        run: cd python && pytest

      - name: Static Analysis
        run: cd python && ruff check .